---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: VBox
lint: |
  yamllint
platforms:
  - name: instance
    box: ubuntu/xenial64
provisioner:
  name: ansible
  lint: |
    ansible-lint
verifier:
  name: ansible
